script:
  - sudo apt-get update && sudo apt get install texlive-recommended texlive-lang-german texlive-latex-extra texlive-polyglossia biber latexmk

before_install:
- "sudo apt-get update && sudo apt-get install texlive texlive-luatex texlive-lang-german texlive-latex-extra latexmk"

script:
- cd bach-arbeit\ copy-pauses/
- latexmk -pdflatex=lualatex -pdf *.tex

notifications:
  on_success: never
  on_failure: never
