before_install:
- "sudo apt-get update && sudo apt-get install texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-polyglossia latexmk"

script:
- cd bach-arbeit\ copy-pauses/
- latexmk -pdflatex=lualatex -pdf *.tex

notifications:
  on_success: never
  on_failure: never
