os: linux

sudo: required

apg_packages:
  - texlive-recommended
  - texlive-lang-german
  - texlive-latex-extra
  - latexmk



script:
  latexmk - pdflatex=lualatex -pdf *.tex

notifications:
  on_success: never
  on_failure: never
