os: linux

sudo: required

before_install:
  - "sudo apt-get update && sudo apt get install texlive-recommended texlive-lang-german texlive-latex-extra latexmk"

script:
  - latexmk - pdflatex=lualatex -pdf *.tex

notifications:
  on_success: never
  on_failure: never
